// User auth
export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const SET_DARK_MODE_PREFERENCE = 'SET_DARK_MODE_PREFERENCE';

// Shiny hunts
export const SET_ACTIVE_HUNTS = 'SET_ACTIVE_HUNTS';
export const ADD_NEW_HUNT = 'ADD_NEW_HUNT';
export const UPDATE_HUNT = 'UPDATE_HUNT';
export const REMOVE_HUNT = 'REMOVE_HUNT';

export const SET_COMPLETED_HUNTS = 'SET_COMPLETED_HUNTS';
export const ADD_COMPLETED_HUNT = 'ADD_COMPLETED_HUNT';

export const SET_FOCUSED_HUNT = 'SET_FOCUSED_HUNT';

export const QUICK_HUNT_UPDATE = 'QUICK_HUNT_UPDATE';
export const REVERT_QUICK_HUNT_UPDATE = 'REVERT_QUICK_HUNT_UPDATE';

// Shinydex
export const SET_SHINYDEX = 'SET_SHINYDEX';
export const ADD_NEW_SHINYDEX_ENTRY = 'ADD_NEW_SHINYDEX_ENTRY';
export const UPDATE_SHINYDEX_ENTRY = 'UPDATE_SHINYDEX_ENTRY';
export const REMOVE_SHINYDEX_ENTRY = 'REMOVE_SHINYDEX_ENTRY';