// User auth
export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';

// Shiny hunts
export const SET_ACTIVE_HUNTS = 'SET_ACTIVE_HUNTS';
export const ADD_NEW_HUNT = 'ADD_NEW_HUNT';
export const UPDATE_HUNT = 'UPDATE_HUNT';
export const REMOVE_HUNT = 'REMOVE_HUNT';

export const SET_COMPLETED_HUNTS = 'SET_COMPLETED_HUNTS';
export const ADD_COMPLETED_HUNT = 'ADD_COMPLETED_HUNT';

export const SET_FOCUSED_HUNT = 'SET_FOCUSED_HUNT';

// Shinydex
export const SET_SHINYDEX = 'SET_SHINYDEX';
export const ADD_NEW_SHINYDEX_ENTRY = 'ADD_NEW_SHINYDEX_ENTRY';
export const UPDATE_SHINYDEX_ENTRY = 'UPDATE_SHINYDEX_ENTRY';
export const REMOVE_SHINYDEX_ENTRY = 'REMOVE_SHINYDEX_ENTRY';